### ISSUE TITLE
Add LocalSettings config for ID format

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/PersistentPageIdentifiers#26]
AC:
* [ ] `$wgPersistentPageIdentifiersFormat` in LocalSettings
* [ ] Use `$1` for the placeholder (similar to https://www.mediawiki.org/wiki/Manual:$wgArticlePath)
* [ ] When displaying the ID, interpolate the format string and the ID
* [ ] Escape the interpolated string

**Comment by JeroenDeDauw** [comment]
>  Create PrefixingIdGenerator

I am wary of persisting the prefixed form. That will make changing the prefix a pain. On the flip side, it allows for changing the prefix of only new IDs, while keeping the old ones the same.

What about only persisting the core ID and expanding it before outputting it anywhere?

>  Prepend this string to the generated ID

If we have such config anyway, we could allow for arbitrary string interpolation instead of only prefixing. Perhaps wgPersistentPageIdentifiersFormat

**Comment by malberts** [comment]
> What about only persisting the core ID and expanding it before outputting it anywhere?

Makes sense. Let's go with that.

> wgPersistentPageIdentifiersFormat

That'll work too.
